### ISSUE TITLE
The client should not die ungracefully if an error is encoutered

### ISSUE THREAD

**Issue by vypxl** [umgefahren/server-language-benchmark#39]
Currently, the client panics whenever anything goes wrong at all.

Two problems that occur often are:
1. Server response is invalid
2. Server closes unexpectedly

In these cases (or others), the client should log that an error occurred and then exit gracefully with a non-zero exit code.

**Comment by tectrixer** [comment]
what do you mean with exit gracefully with non zero exit code? That is basically panicking in Rust

**Comment by vypxl** [comment]
I mean logging something readable like `Server reset connection. Exiting...` instead of

```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }', src/benchmark.rs:56:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(...)', src/benchmark.rs:212:38
```

**Comment by tectrixer** [comment]
There are some deep errors in the client, it needs a rework and not just better logging. See #44 for more information
