### ISSUE TITLE
Client is broken

### ISSUE THREAD

**Issue by tectrixer** [umgefahren/server-language-benchmark#44]
This error shows up 50 times or more when running the benchmark. Occurs both for Swift and Dart:

`thread 'tokio-runtime-worker' panicked at 'called 'Result::unwrap()' on an 'Err' value: Os { code: 49, kind: AddrNotAvailable, message: "Can't assign requested address" }', src/benchmark.rs:47:53`

**Comment by vypxl** [comment]
I think this is no longer relevant once we have the new client.
