### ISSUE TITLE
Better Specify DUMPINTERVAL

### ISSUE THREAD

**Issue by vypxl** [umgefahren/server-language-benchmark#65]
The DUMPINTERVAL command is missing concrete specification:

- What should be returned by the server after a DUMPINTERVAL command?

The Go implementation currently returns xxhxxmxxs, corresponding to the supplied interval. This should at least be changed to correspond to the specified duration format.

- Should the old interval be cleared and the new one immediately started?
  - There are multiple ways this could be handled:
    - Wait until the last interval runs out and schedule the next dump with the new interval
    - Cancel the last interval, create a dump immediately and schedule the next dump with the new interval
    - Cancel the last interval and schedule the next dump with the new interal
 
The go implementation currently uses the third approach (correct me if I'm wrong) and I think this should be the way to go.

**Comment by Zollerboy1** [comment]
I would also take the third approach but the server should respond with something like 'OK' after it has rescheduled the recurring dumper.
