### ISSUE TITLE
Fix specification for Duration

### ISSUE THREAD

**Issue by Zollerboy1** [umgefahren/server-language-benchmark#67]
Currently, the specification requires that a parsed duration shall match the following RegEx in total:

```
([0-9][0-9])h-([0-9][0-9])m-([0-9][0-9][0-9])s
```

This seems wrong, since normally seconds are only written using two digits.
Additionally, it allows second and minute values larger than 59.

Therefore, I suggest that the requirement is changed to this RegEx instead:

```
([0-9][0-9])h-([0-5][0-9])m-([0-5][0-9])s
```

**Comment by vypxl** [comment]
I agree
