### ISSUE TITLE
Correctly specify behaviour of commands consisting of multiple steps

### ISSUE THREAD

**Issue by Zollerboy1** [umgefahren/server-language-benchmark#70]
Right now there are two commands that initiate a simple protocol consisting of several steps that have to be followed by both the server and the client: `UPLOAD` and `DOWNLOAD`.

However it is not fully specified what the server should do in case it either gets no answer when it's expecting one (e.g. after an unexpected disconnect) or when it gets a wrong answer (e.g. when the client responds with neither `OK` nor `ERROR` in step 4 of the `UPLOAD` protocol, but with something else).

I suggest that the server should cancel an ongoing operation when there was a disconnect or when it gets an unexpected response from the client (for the `UPLOAD` command this means deleting the created file).
It could also be worth adding a timeout to the protocols, i.e. both the server and the client should only wait a certain amount of time (e.g. 2s) for a response before cancelling the protocol.

**Comment by vypxl** [comment]
As this is a benchmark, I do not think we have to implement such checks into the servers. Of course, `ERROR` should cancel the current operation on both sides, but I think that is obvious.

Timeouts and such could be implemented into the benchmark client. Upon any error, the benchmark can just fail as it is extremely unlikely that such things happen in the controlled environment we have.

**Comment by Zollerboy1** [comment]
Yeah, that's actually a good point.
