### ISSUE TITLE
Client should wait for the server to go online

### ISSUE THREAD

**Issue by vypxl** [umgefahren/server-language-benchmark#9]
To automate the benchmarking process, the client should not die just because the server is not yet online, it should rather wait until a connection can be established before beginning the benchmark process.

**Comment by tectrixer** [comment]
Should this only be when choosing the benchmark option, or also for the execute single actions option?

**Comment by tectrixer** [comment]
@vypxl I added a pull request which should fix this and implement the optimal behaviour: #12

**Comment by vypxl** [comment]
Looks good, I would propose to add a Log entry like `Server not up yet, waiting...` in the case of a failure, such that the client does not quietly wait forever if something goes wrong.

**Comment by tectrixer** [comment]
It does log `Waiting for server to start...` to stdout, or do you mean something else?

**Comment by tectrixer** [comment]
Fixed in PR #12
